### PR TITLE
add command to view allocation stats, rename dumpleak to mdumpleak

### PR DESCRIPTION
**Pull request by andrewchambers**

### CODE REVIEW

**Comment by oridb** [comment]
Would it make sense to merge the two commands? or at least share code?

**Comment by andrewchambers** [comment]
when they are so simple i'm not sure, but if we add features it is probably smarter to do that. Or even make a support lib for handling the trace files.

**Comment by andrewchambers** [comment]
The lib would really just be callback based atm if anything.

**Comment by oridb** [comment]
I was thinking sharing the loading code, but you're probably right.

Might be worth just adding it as an option to the one binary, though.

**Comment by oridb** [comment]
Merged the tools in a separate commit. Closing this one.

**Pull request closed without merging**
