### PR TITLE
Add tupget to qbe backend.

### PR DESCRIPTION
**Pull request by andrewchambers**

### CODE REVIEW

**Comment by oridb** [comment]
Going to hold off until Otup works, since otherwise there's no sane way of testing.

**Comment by andrewchambers** [comment]
Sure - let me know if its blocking you. There is no need to wait for me if you can do something faster.

**Comment by oridb** [comment]
I'm busy for this weekend -- I may get some time, but I'm not expecting too much hacking in the next few days.

**Comment by oridb** [comment]
Pretty sure this is obsolete -- closing.

**Pull request closed without merging**
